export const HEADER_TYPES = {
  SET_TITLE: "SET_TITLE",
  SET_COLOR: "SET_COLOR",
};

export const ERROR_TYPES = {
  ADD_ERROR: "ADD_ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",
};

export const POSTS_TYPES = {
  FETCH_POST_LIST: "FETCH_POST_LIST",
  FETCH_POST_LIST_PENDING: "FETCH_POST_LIST_PENDING",
  FETCH_POST_LIST_FULFILLED: "FETCH_POST_LIST_FULFILLED",
  FETCH_POST_LIST_REJECTED: "FETCH_POST_LIST_REJECTED",
  FETCH_POST: "FETCH_POST",
  FETCH_POST_PENDING: "FETCH_POST_PENDING",
  FETCH_POST_FULFILLED: "FETCH_POST_FULFILLED",
  FETCH_POST_REJECTED: "FETCH_POST_REJECTED",
  SET_SELECTED_POST: "SET_SELECTED_POST",
};

export const COMMENTS_TYPES = {
  FETCH_COMMENTS_LIST: "FETCH_COMMENTS_LIST",
  FETCH_COMMENTS_LIST_PENDING: "FETCH_COMMENTS_LIST_PENDING",
  FETCH_COMMENTS_LIST_FULFILLED: "FETCH_COMMENTS_LIST_FULFILLED",
  FETCH_COMMENTS_LIST_REJECTED: "FETCH_COMMENTS_LIST_REJECTED",
};
